name: pubpub
description: "PubPub - Cross-platform Pub mirror browser"
publish_to: 'none'
version: 0.2.4+7

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  dio_web_adapter: ^1.0.1
  hive_flutter: ^1.1.0
  tdesign_flutter: ^0.2.1
  json_annotation: ^4.9.0
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.7
  chinese_font_library: ^1.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - logo.png
    - assets/td_theme.json
